version: '3.7'
services:
  spark-master:
    image: bitnami/spark:latest
    command: bash -c "bin/spark-class org.apache.spark.deploy.master.Master && /sbin/start-connect-server.sh --packages org.apache.spark:spark-connect_2.12:3.5.0"
    ports:
      - "9090:8080"
      - "7077:7077"

  spark-worker-1:
    image: bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077

  backend:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.backend
    depends_on:
      - spark-worker-1
    ports:
      - "5000:5000"
    volumes: 
      - ./:/app
    tty: true
    stdin_open: true
