FROM python:3.11-slim

COPY --from=openjdk:11-jre-slim /usr/local/openjdk-11 /usr/local/openjdk-11

ENV JAVA_HOME /usr/local/openjdk-11

RUN update-alternatives --install /usr/bin/java java /usr/local/openjdk-11/bin/java 1

RUN apt-get -y update

RUN apt-get -y install git

WORKDIR /app

RUN pip install --no-cache-dir Flask pyspark pyspark[sql] pyspark[pandas_on_spark] plotly pyspark[connect] pandas numpy matplotlib pyarrow

COPY . /app

CMD [ "python" ]
